#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

# Check staged files
npx lint-staged ||
(
    echo '🤮 Its FOKING RAW - Your styling looks disgusting.
            Staged files Check Failed. Run npm run format, add changes and try commit again.';
    false;
)

# Check Prettier standards
npm run format ||
(
    echo '🤮 Its FOKING RAW - Your styling looks disgusting.
            Prettier Check Failed. Run npm run format, add changes and try commit again.';
    false;
)

# Check ESLint Standards
npm run lint ||
(
        echo '😤 Get that weak shit out of here!
                ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false;
)

# Check tsconfig standards
npm run type-check ||
(
    echo '❌ Failed Type check.
            Are you seriously trying to write that? Make the changes required above.'
    false;
)

## Run tests
#pnpm run test ||
#(
#    echo '🤡😂❌🤡 Failed Test. 🤡😂❌🤡
#            Are you seriously trying to write that? Make sure you pass all tests and try to commit again.'
#    false;
#)

# If everything passes... Now we can build
echo '🤔... Alright.... Code looks good to me... Trying to build now.'

npm run build ||
(
    echo '❌ Better call Bob... Because your build failed
            Next build failed: View the errors above to see why.
    '
    false;
)

# If everything passes... Now we can commit
echo '✅ You win this time... I am committing this now.'
